/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ds1307.h"
#include "lcd.h"

int main(void)
{
	lcd_init();

	while(1)
	{
		lcd_display_clear();

		lcd_display_return_home();
		lcd_print_string("RTC Test....");
		for(uint32_t i; i <=1000; i++);
	}

}
